### ISSUE TITLE
Infinite Scroll Demo Missing?

### ISSUE THREAD

**Issue by kawalsh** [desandro/masonry-docs#20]
I followed a link from the masonry-rails gem github (https://github.com/kristianmandrup/masonry-rails), which implied that there should be an infinite scroll demo on this page (http://masonry.desandro.com/demos/infinite-scroll.html)

Not a big deal, just thought you should know.

**Comment by desandro** [comment]
Thanks for reporting this issue. Closing as a duplicate of #1

**Comment by guykatz** [comment]
so is there an infinite scroll baked into masorny or not?
thanks!
