### ISSUE TITLE
Masonry keeping its order in this specific case, why?

### ISSUE THREAD

**Issue by MvBeurden** [desandro/masonry-docs#22]
I'm working with Masonry and not getting the expected results.

See the following Pen: http://codepen.io/anon/pen/VLrjme

Why does box number 5 not move to the upper-right corner, next to number 3? There is enough space there and to my understanding this is what Masonry does. I get the impression the issue lies within the percentage-sizing, but this should be possible according to Masonry's docs.

EDIT: if I try it with more columns I can get it to work, so the problem is in the 2-column layout. It is not rounding - I have already tried 49,5% widths and even 45% - the grid seems to break as soon as there are 2 columns intended.

**Comment by desandro** [comment]
Gaps may occur in Masonry layouts. If you prefer for gaps like this to be filled, use [Packery](http://packery.metafizzy.co/).
