### ISSUE TITLE
masonry don't support require.js

### ISSUE THREAD

**Issue by liuliangsir** [desandro/masonry-docs#24]
![image](https://cloud.githubusercontent.com/assets/8049878/9054682/88bcd0c6-3ab6-11e5-87d9-93e5b4712767.png)
![image](https://cloud.githubusercontent.com/assets/8049878/9054693/a58b547a-3ab6-11e5-9142-acf9e8935873.png)

**Comment by desandro** [comment]
Closing here. See desandro/masonry#735
