### ISSUE TITLE
Pixel problem

### ISSUE THREAD

**Issue by glmarco24** [desandro/masonry-docs#25]
Hello,

I have a weird problem, it happens because browsers (some of them) rounds image sizes on 1 px. Bigger images are 1920x2160, smaller 1920x1080. Container width is 1908px. Column width is 25%, and that makes smaller image 477x268, and big ones 477x537.
268*2 is 536px and that columns (two of them in a middle on attachment) are shorter for a pixel!

Small image is 268.5px, but some browsers rounds that number on 268.

Now, user should have option to add different sizes of images and create real masonry, but if he adds images with dimensions i wrote up, I guess he will expect to get grid.

If you have any ideas how to solve this please let me know :)

Thanks!

![masonry](https://cloud.githubusercontent.com/assets/13031419/9529692/0d03548e-4cfc-11e5-891b-502ef0ee6549.jpg)

**Comment by desandro** [comment]
Sorry to say this is a simple pixel rounding error. While a CSS layout would calculate the same height for the various blocks, in JavaScript, a pixel might be rounded differently. Thus the two center columns will are 1px shorter, so the items appear in the center.

Unfortunately, there's no reliable fix for this :cry:

**Comment by andreyvolokitin** [comment]
Maybe it is possible to manually check each "column" height on ```layoutComplete``` and if there are any misalignments - fix them. Maybe it is even could be done inside lib itself?
