### ISSUE TITLE
Recommend setting extra width to accommodate gutter

### ISSUE THREAD

**Issue by rayshan** [desandro/masonry-docs#28]
Hi Dave! In order to get to this layout: http://codepen.io/desandro/pen/gbnko

A user needs to add a multiple of the gutter width set in JS in the 2x / 3x... grid item's CSS class as well. Same for vertical gutter. Otherwise layout doesn't perfectly line up. This wasn't immediately clear to me. Sometime to consider.

**Comment by desandro** [comment]
Thanks for the input. Yeah, it can be a bit confusing. It's hard to explain with words. Rather than do that, I'd prefer to use demos and let readers learn from those.
