### ISSUE TITLE
Stacking

### ISSUE THREAD

**Issue by leocavallini** [desandro/masonry-docs#31]
I'm photographer and built my portfolio in March 2014 or so, using Wordpress and Masonry for the thumbnails.
Now it looks something is broken. I updated the .js and didn't solve. Last week the thumbnails wouldn't show and now it's getting stacked.
See any of the categories here, it will load correctly on first visit. But revisiting a category again will make the thumbnails stack: http://www.leocavallini.com/
Shift + reloading the page (or changing browser window size like fullscreen or maximize / restore) seems to fix and load the thumbnails correctly, but if I revisit the page again, it will break my layout.
Any clue?
Thanks...

**Comment by desandro** [comment]
See http://masonry.desandro.com/faq.html#how-do-i-fix-overlapping-item-elements
