### ISSUE TITLE
Extra 6px vertical gaps in all browsers in Windows

### ISSUE THREAD

**Issue by g1un** [desandro/masonry-docs#34]
Hello!
I can't understand what is wrong with my code. There are 6px extra vertical gaps as on image.
![image](https://cloud.githubusercontent.com/assets/13907881/11022442/3e2ab202-8670-11e5-9ba5-623eb9d0786c.png

)
You can download zip with issue http://test.g1un.ru/issue.zip or see the site here http://g1un.ru/dochery/design_case.html

imagesLoaded doesn't help.

Thank,
Ilia

**Comment by desandro** [comment]
It may be caused by the scrollbar. Try setting `html { overflow-y: scroll; }` in your CSS.

**Comment by g1un** [comment]
Thanks a lot! It works!
I'm really "not very smart", if i haven't ask you for help earlier.)
Now i can finally say "Huuuuuuh!" and move on.
Thanks!
