### ISSUE TITLE
bad arrangment of items

### ISSUE THREAD

**Issue by mocotrah** [desandro/masonry-docs#36]
Hi,
I would like to show you the following issue. 
Using the codepen examlpe you provide, change the following
- in the css change the class .grid-item--width2 { width: 340px; }
- in the html 
<pre><code>
&lt;div class="grid">
  &lt;div class="grid-item grid-item--width2 grid-item--height2"></div>
  &lt;div class="grid-item grid-item--width2 grid-item--height2"></div>
  &lt;div class="grid-item grid-item--width2 grid-item--height2"></div>
&lt;/div>
</code></pre>
(resize the browser to trigger the repositioning)
You'll see that the tiles will be positioned like they have a padding. (see screenhot I have attached).
I would have expect they arrange in a single row one next to each other.

![image](https://cloud.githubusercontent.com/assets/15890374/11212433/1328dc6a-8d36-11e5-8fc0-9a531af40459.png)

**Comment by mocotrah** [comment]
another example
leave the css with default values .grid-item--width2 { width: 320px; }
but change the html to
<pre><code>
&lt;div class="grid">
  &lt;div class="grid-item grid-item--width2 grid-item--height2"></div>
  &lt;div class="grid-item grid-item--width2 grid-item--height2"></div>
  &lt;div class="grid-item grid-item--width2 grid-item--height2"></div>
  &lt;div class="grid-item grid-item--width2 grid-item--height2"></div>
  &lt;div class="grid-item grid-item--width2 grid-item--height2"></div>
  &lt;div class="grid-item grid-item--width2 grid-item--height2"></div>
  &lt; class="grid-item grid-item--width2 grid-item--height2"></div>
  &lt;div class="grid-item grid-item--width2 grid-item--height2"></div>  
&lt;/div>
</code></pre>
![image](https://cloud.githubusercontent.com/assets/15890374/11213927/fa9035dc-8d3e-11e5-8fa3-1193dcd11c71.png)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by mocotrah** [comment]
Hi, I have created the reduced test case.
http://codepen.io/mocotrah/pen/WQmGMN 
it is forked from "Masonry - isFitWidth" and changed only 
.grid-item  =>  width: 400px;

**Comment by mocotrah** [comment]
I think I got the ideea... the width of tiles must be a multiple of columnWidth ?

**Comment by desandro** [comment]
Yes. setting `columnWidth: 400` will resolve this issue.
