### ISSUE TITLE
Items arrange themselves to be in lines

### ISSUE THREAD

**Issue by apichris** [desandro/masonry-docs#37]
Hello from Thailand,
At first, I have to say that I'm new to coding.  
My weird arrangement can't be forked on codepen. However, I've created one
http://codepen.io/apichris/pen/NGQbre

This pen is what I partly have on my Wordpress production site: http://www.livingexpert.co/for-sale/
As you can see from my real site, items adjust themselves to be in line, not in masonry grid
I have tried to figure it out for a week but I still can't get it right.

FYI:
1) I don't really know why but 'gutter' doesn't work on my site,  
So I use 'margin-left' on grid-item instead. On this pen, if you remove margin-left and put gutter back, the result will be perfect. However, even if I remove the margin and put back gutter, the arrangement won't be changed.
2) HTML was generated from php which I can't delete height and width of <img> for the_post_thumbnail()
3) So, I use 'height: auto' for item to adjust itself according to post thumbnail's proportion.

Do you have any idea?  Please help.
Thank you very much

**Comment by desandro** [comment]
`columnWidth` should be equal to a multiple of an item's outer width. This includes horizontal margin. One solution is to increase `columnWidth` by the size of the margin. See demo http://codepen.io/desandro/pen/9eddae91b97c14ecfc914a5474d20aa0/

``` css
.grid-item {
  width: 350px;
  float: left;
  margin-bottom: 2em;
  margin-right: 20px;
}
```

``` js
$('.grid').masonry({
  columnWidth: 370 // 350 width + 20px margin
})
```

**Comment by apichris** [comment]
Hi,

Thanks a lot for helping me. 
I tested already on my site but it didn't change the arrangement. 

As I see now, I think maybe it's about some setting on Jupiter theme. I will try to figure it out.

Anyway, do you have another suggestion? This may be my last question because I don't want to bother you that much. 

Thank you for your answer.
