### ISSUE TITLE
Hide or fade out or overlay with blank by rotating on mobile devices

### ISSUE THREAD

**Issue by ezkay** [desandro/masonry-docs#38]
Hi,

if you rotate a mobile device, as we know, the browser turns the whole site. Now now the grid resizes. If I don't want to see this happening, even with transisionDuration: 0, would a overlay or something be possible?

**Comment by desandro** [comment]
Possible solutions:

+ Prevent page width changing on orientation change
+ Set a fixed width on the container
+ Try using [percentPosition](http://masonry.desandro.com/options.html#percentposition) with percentage-width items
