### ISSUE TITLE
When the first element is hidden, all visible elements fall into a single column

### ISSUE THREAD

**Issue by dimitritron** [desandro/masonry-docs#39]
I have a scenario where elements are shown or hidden (using the css display property) according to  a user selection. Masonry is used to order the visible elements.

This works fine as long as the first element is among the visible elements. When it is not, masonry seems to trip and organises all the elements in a single column. 

I tried being smart with the item selectors, but could not achieve the desired result. I ended up solving the problem with this nifty line of code: 
`$("#posts").prepend($('#posts .post:visible:first')).masonry();`

Of course, this will reorganise the elements. This is not an issue in my scenario, but isn't an ideal solution for all cases.

It seems to me this is a bug in masonry?

**Comment by desandro** [comment]
Thanks for reporting this issue. See https://github.com/desandro/masonry/issues/668#issuecomment-75750164 . Closing  here as a duplicate
