### ISSUE TITLE
Overlapping images

### ISSUE THREAD

**Issue by robin2016** [desandro/masonry-docs#40]
Good morning , it's my first time and my English is bad :) I am using masonry and I have a problem of overlapping images. I enclose a screenshot. On my pc the problem exists only on maxthon , but the problem exists on other PCs for all browsers. Link: http://www.casabertagni.it/casa-bertagni/gallery/
Thanks and best regards.

![cattura](https://cloud.githubusercontent.com/assets/16574823/12141349/ea4b0ec0-b46e-11e5-8b26-0fff777f91cb.JPG)

**Comment by desandro** [comment]
See http://masonry.desandro.com/faq.html#how-do-i-fix-overlapping-item-elements
