### ISSUE TITLE
Angularjs

### ISSUE THREAD

**Issue by nmpribeiro** [desandro/masonry-docs#42]
Hi there,

I am having a little trouble implementing this with angularjs. My problem seams to be that since I insert the images with angular {{ item.img }}, imagesloaded cannot understand if it has been already downloaded. This is also because I download them in advance on virtual dom so the user doesn't feel any performance issue.

Have you seen masonry implemented in angular js?
Thanks

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

Sounds like you'll need a way to trigger `imagesLoaded` on the new content. Typically this looks something like

``` js
var $data = $(data).imagesLoaded( function() {
  ...
})
```

**Comment by nmpribeiro** [comment]
Yes. Actually, it is better to build upon what other made. For instance:
https://github.com/passy/angular-masonry

Then I have a directive:
```
.directive('onImgLoad', ['$parse', function ($parse) {
    return {
      restrict: 'A',
      link: function (scope, elem, attrs) {
        var fn = $parse(attrs.onImgLoad);
        elem.on('load', function (event) {
          scope.$apply(function() {
            fn(scope, { $event: event });
          });
        });
      }
    };
  }])
```
That basically allows me to trigger a function if I place it on the:
```
<img on-img-load="notifyImgLoad($index)"/>
```
This way, everytime an image get's loaded, I can use that function to broadcast a masonry.reload event:
```
    var loadedCount = 0;
    $scope.notifyImgLoad = function(index) {
      loadedCount++;
      if (loadedCount === $scope.projectItems.length) {
        console.log('Triggering reload');
        $rootScope.$broadcast('masonry.reload');
      }
    };
```
Basically I don't need a bunch of masonry.reloads being broadcasted, just the last one when all is loaded.

Credit for the solution: I found multiple parts around, but check this thread: https://github.com/passy/angular-masonry/issues/4

Thanks @desandro  Now it works as suposed.
