### ISSUE TITLE
AngularJS inactive tab problem

### ISSUE THREAD

**Issue by nmpribeiro** [desandro/masonry-docs#43]
Hi,

So... using my AngularJS aproach discussed in issue #42 , whenever I get out of the tab and leave it inactive for suficient time, when I go back to it, all masonry content is way at the bottom of the page. Resizing the window doesn't fix this, and seams the problem is the .grid-items are with way too much 'top' value.
@desandro do you know why this might be occuring?

I don't know how masonry does these cool effects nor unfortunately have the time to dive into the code.
Thanks mate!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by nmpribeiro** [comment]
Behaviour disapeared. Can't replicate it. Might be a browser issue.
