### ISSUE TITLE
Overlapping images after window resize

### ISSUE THREAD

**Issue by ryanwebdev** [desandro/masonry-docs#44]
Hi, I am using bootstrap with masonry to make a responsive grid. Here is the example I made. http://codepen.io/anon/pen/XXBNBx

When I tried to resize the window from 3 column down to 1 column, the images overlap each other. I have included the imageLoad JS, but the bug is still there.

**Comment by desandro** [comment]
Hello! Thanks for reporting this bug. Looks like this is the same issue as https://github.com/desandro/masonry/issues/427#issuecomment-50423923

Setting a default width looks to be the fix. See [demo on CodePen](http://codepen.io/desandro/pen/fcffbe097d0442cb05d60312a2772ed8/)
