### ISSUE TITLE
Layout refresh problem on mobile devices when the the orientation is changed.

### ISSUE THREAD

**Issue by kazo22** [desandro/masonry-docs#46]
Hi,

with Samsung's default browser or Dolphin's web browser the layout brokes when you change the orientatition of the device. Even the http://masonry.desandro.com/ homepage. With Firefox and Chrome for mobile, everything is OK. I tried to use jquery.mobile to reload or destroy/create the layout, on the orientationchange event, but it's not working. The layout became usabale only when the whole page is reloaded.

Thank you!
kazo22.

**Comment by desandro** [comment]
Thanks for reporting this issue. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by fspezi** [comment]
I am the same issue. I tested with "Samsung Galaxy S3 Neo" and "Samsung Galaxy S5".

I try to open `http://masonry.desandro.com/layout.html`.  
The "Item sizing" demo does not recalc positions.  
The "Responsive layouts" works well.
First "imagesLoaded" demo shows images over others.
Second "imagesLoaded" demo do not recalc positions.
