### ISSUE TITLE
How to change layout?

### ISSUE THREAD

**Issue by Nic787** [desandro/masonry-docs#47]
Hi,

I would like to create something like that, but I don't know if it work with masonry or only floating elements?
http://image.noelshack.com/fichiers/2016/07/1455724726-capture-d-ecran-2016-02-17-a-10-54-01.png
http://image.noelshack.com/fichiers/2016/07/1455724726-capture-d-ecran-2016-02-17-a-10-54-12.png

I'm not really familiar with javaScript, so I need a bit of help. Should I have div with photo as background or img element? How could I write the photo title in the middle of the big photo?

Thank you

**Comment by desandro** [comment]
Yes Masonry can be used for this layout. As for centering of images, I'll leave that up to you. Sorry but I won't be able to help guide this one.

**Comment by Nic787** [comment]
I'm a bit lost. I created a new question on Stackoverflow : http://stackoverflow.com/questions/35804935/how-to-set-two-divs-side-by-side-with-the-same-height

I would like to always have 1 big image and 2 small images on the side, but masonry seem to just fit everything depending of image size... I need something that can change image width dynamically to get the same div height. Not sure if it's possible.
