### ISSUE TITLE
Issue when calling .masonry events after it has been initialized.

### ISSUE THREAD

**Issue by yoxalld** [desandro/masonry-docs#48]
Thanks for taking the time to look over this issue! 

I am having an issue when trying to call masonry events after it has been set up. I am retrieving new content via ajax and trying to add those items into the masonry layout during the .done function in ajax. I have included in the code the various ways I have tried to make it work all to no effect. I'm not getting errors when I call the masonry events so it seems that they are present they just don't do anything.

When I try using the appended event and pass it the jQuery object of elements nothing happens at all. But when I append the elements with jQuery's append() they get added to the page(the layout is messed up though) but I am then not able to get any of the masonry layout events to actually update the layout.

The html code is lengthy so I won't include it here. But when I view it I can see that the new elements have been added but they do not have the inline styling that is added by the masonry plugin.
Below is the relevent js code.

Please let me know if there is any more information I can provide to help figure this issue out. Thanks!

    (function($) {
	$(function() {
		if( $('.masonry-container').length ){
			var grid = $('.masonry-container').masonry({
				itemSelector: '.topic-grid'
			});
			grid.imagesLoaded().progress( function() {
				grid.masonry('layout');
			});
			caeidAjaxLoad(grid);
		}
	});
	function caeidAjaxLoad(grid) {
		//console.log(grid);
		//console.log('caeidAjaxLoad has started');
		if( caeidAjax.ajaxPage === '1' ){
			//console.log('ajaxPage found');
			var pageNum = parseInt(caeidAjax.startPage) + 1;
			var max = parseInt(caeidAjax.maxPage);
			var nextLink = caeidAjax.nextLink;
			var ajaxLoadingText = '<div class="row text-center caeid-ajax-loading"><i class="fa fa-spinner fa-pulse"></i> Loading More</div>';
			var ajaxLoading = false;
			if( pageNum <= max ) {
				//console.log('not on last page');
				$(window).scroll(function(){
					if( $(window).scrollTop() >= $(document).height() - $(window).height() - 400 && ajaxLoading === false ){
						console.log('this should trigger the loading wheel');
						ajaxLoading = true;
						$('#page-main .container').append(ajaxLoadingText);
						console.log('nextLink: ', nextLink);
						$.ajax({
							type        : 'GET',
							url         : nextLink,
							dataType    : 'html',
							encode      : true
						}).done(function(data) {
							var newElements = $(data).find('.topic-grid');
							/*Everything up to this point works just fine. It's what comes after this that I'm having issues with*/

							/*This didn't do anything*/
							// grid.masonry('appended', newElements);
							/*So I tried this, which adds the new items to the page, but the layout is all messed up*/
							// grid.append(newElements);
							/*So I tried calling this. Which did nothing.*/
							// grid.masonry('layout');

							/* So I though I would try recalling the entire masonry function. Which adds the elements to the page still but masonry still does nothing*/
							grid.append(newElements);
							grid.masonry({
								itemSelector: '.topic-grid'
							});
							grid.imagesLoaded().progress( function() {
								grid.masonry('layout');
							});
						});
					}
				}); 
			}else{
				// Haven't written this part yet
			}
		}
	}
    })(jQuery);

**Comment by desandro** [comment]
Try this!

``` js
.done(function(data) {
    var newElements = $(data).find('.topic-grid');
    // add new elements to page
    grid.append( newElements );
    // add new elements to masonry instance
    grid.masonry( 'appended', newElements );
    // fix layout after image has been loaded
    newElements.imagesLoaded().progress( function() {
      grid.masonry();
    });
});
```

**Comment by yoxalld** [comment]
That did the trick, thanks!
