### ISSUE TITLE
imagesLoaded not responding on page with ajax loaded content

### ISSUE THREAD

**Issue by ChrisVWL** [desandro/masonry-docs#50]
Hi, Masonry is amazing. Thank you. I hope you can help me with a problem I'm having. My wp site uses masonry to layout category posts. All is great using imagesLoaded on the #content div of each page to make sure all image sizes are known to masonry before laying each out. I have a #loading div which I display until imagesLoaded, then I hide #loading and show #content. But #loading never disappears on the page with the ajax call? And there is no response in the console for .always() or .fail()? I don't know where I should be looking.. hashchange? a nested imagesLoaded call or function? The website is: http://www.friendsoftheirvingtonlibrary.org/wordpress/category/book-sale/ (the ajax call governs the loading of the amazon storefront items). I've disabled the css that hides/displays the #content and #loading divs so you can see the content.

**Comment by desandro** [comment]
Looks like you have since stubbed out your imagesLoaded code. If you have a reduced test case showing the issue I can take a look. See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
