### ISSUE TITLE
Safari - "layout" method never done

### ISSUE THREAD

**Issue by FredG-PN** [desandro/masonry-docs#51]
Bonjour,

I have an issue with Safari browser and repositionning blocks after a click event or resize for exemple.

Safari 9 is OK, but with lowers versions, the "refresh" doesn't perform.

Masonry PACKAGED v4.0.0

http://codepen.io/desandro/pen/htsui (click on block to change the shape)

**Comment by desandro** [comment]
Thanks for reporting this issue. This is likely related to desandro/masonry#834 Closing here as a duplicate.
