### ISSUE TITLE
Images loaded page could mention that you need imagesloaded.js

### ISSUE THREAD

**Issue by uglyeoin** [desandro/masonry-docs#52]
http://masonry.desandro.com/layout.html#imagesloaded

This page, it doesn't mention that you need to download imagesloaded.js or give reference to where to get it.  I initially searched masonry website for the download, perhaps a link would be useful.

Thanks for the great product, hope my feedback helps.

**Comment by desandro** [comment]
Good call, updated!

**Comment by uglyeoin** [comment]
Thanks, quick response :)
