### ISSUE TITLE
load-more / load-all function

### ISSUE THREAD

**Issue by comdesign** [desandro/masonry-docs#54]
hi,
first: great work, works perfect for me!

is it possible to add something like a "load more"-button?
 so maybe the first 12 items are shown by default, all further items can be loaded by clicking on "load more" or maybe "load all".

Thanks!

**Comment by desandro** [comment]
Yes, this is possible. You should use the [appended](http://masonry.desandro.com/methods.html#appended)  method to do so. As to how, I'll leave that up to you!
