### ISSUE TITLE
Blocks flicker/load twice in Safari only: Using Masonry, Imagesloaded, Ajax Load More wp plugin

### ISSUE THREAD

**Issue by rbgray** [desandro/masonry-docs#55]
I'm running into a strange issue on Safari and I'm not really sure where it is coming from. The best way I can describe what is happening is when you scroll down the page, the blocks loading in move into place, then disappear, then move into place again and stay.  See video at https://youtu.be/bz62lfOSt3o to see example. Everything works beautifully on Firefox and Chrome, it's just doing this on Safari. Any thoughts to where the issue is?

Below is my masonry coding:

$(document).ready(function(){
	$('.grid').masonry({
	  // options...
	  itemSelector: '.grid-item',
	  columnWidth: 320,
	  gutter:20,
	  isFitWidth: true,
	  isAnimated: !Modernizr.csstransitions
	});
  $('.grid').masonry('reloadItems').masonry();
});

(function($) {
  var masonryInit = true;	// set Masonry init flag
  $.fn.almComplete = function(alm){ // Ajax Load More callback function
    if( $('.grid-lazy').length){
      var $container = $('ul.alm-listing'); // our container
      if(masonryInit){
        // initialize Masonry only once
        masonryInit = false;
          $container.masonry({
            itemSelector: '.grid-item',
            columnWidth: 320,
            gutter:20,
            isFitWidth: true,
            isAnimated: !Modernizr.csstransitions
          });
      } else {
          $container.masonry('reloadItems').masonry();
          $('[data-remodal-id]').remodal();
      }
      $container.imagesLoaded( function() {
	         $container.masonry();
	      });
    }
  };
})(jQuery);

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).

**Comment by rbgray** [comment]
Please see link below. I removed the ajax-load-more scripts to see if that was part of the problem, but in Safari on load there is still a "bounce" to the blocks. 

http://codepen.io/rbgray/pen/VjYory

**Comment by desandro** [comment]
Thanks for that. The issue is most likely active transition on `grid-item`.

``` css
.grid-item {
  transition: left .4s ease-in-out, top .4s ease-in-out .4s;
}
```

You may be able to fix this issue by removing that CSS.

See http://isotope.metafizzy.co/faq.html#items-jump-after-transitioning-position
