### ISSUE TITLE
Problem loading last gallery item

### ISSUE THREAD

**Issue by taraurso** [desandro/masonry-docs#57]
Hi, I have the masonry grid in one of the wordpress themes I'm working with and in one of the galleries, I want to have infinite scroll but this portfolio is sectioned into different categories and for the "community" one, the very last gallery item wouldn't ever show up so I added the load more button, but it's not ideal.

Any chance anyone knows how to make the infinite scroll work even when there are only two items, like here: http://goo.gl/x2DUan (click community).

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Masonry. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/desandro/masonry/blob/master/.github/contributing.md#submitting-issues).
