### ISSUE TITLE
Margin top or bottom blank between img

### ISSUE THREAD

**Issue by W-prog** [desandro/masonry-docs#59]
Hello, I have this margin on the web site ; http://galeriemimosas.com/
Can you help me to fixed it ?
My CSS : 
[code]
.grid-sizer,
.grid-item { width: 20%; }
.grid-item {
  float: left;
}
    .grid-item img{
        width:100%;
        overflow:hidden;
    }

/* 2 columns */
.grid-item--width2 { 
    width: 40%; 
}
[/code]
Best regards.

**Comment by desandro** [comment]
Sorry, I do not provide personal support for implementation issues with Masonry.
