### ISSUE TITLE
Margin between divs wrong

### ISSUE THREAD

**Issue by JulianPorras** [desandro/masonry-docs#61]
Hi!
I have: 

```
.grid-item {
  float: left;
  width: 300px;
  height: 300px;
  margin: 5px;
  padding: 5px;
  background-color: red;
}

.grid-item--width2 {
  width: 600px;
}

.grid-item--height2 {
  height: 600px;
}
```

```
<div class="grid content-grid">    
    <div class="grid-item"></div>   
    <div class="grid-item grid-item--width2 grid-item--height2"></div>   
    <div class="grid-item"></div>
</div>
```

and the result is:

![screen shot 2016-08-08 at 08 22 44](https://cloud.githubusercontent.com/assets/17885110/17481185/51ac88a2-5d41-11e6-884d-b74472267245.png)

**Comment by diegosomar** [comment]
I have the same issue! Can you solved this?

**Comment by diegosomar** [comment]
Finally I solved this.
In my case I am using the width as percent.
I sawyed [here](https://stackoverflow.com/questions/30935502/masonry-column-width-percent-gutter) that you need to subtract the gutter to the grid-item width. Than works for me!

My code is now like that:

`.grid-sizer, .grid-item--width1x { width: calc(20% - 30px); }`
`.grid-item--width2x { width: calc(40% - 30px); }`
`.grid-item--width3x { width: calc(60% - 30px); }`
`.grid-item--width4x { width: calc(80% - 30px); }`
